### ISSUE TITLE
Missing processor

### ISSUE THREAD

**Issue by LcTrKiD** [facebook/Recipes-for-AutoPkg#52]
I'm getting this error: 
``` ✘ joaquin  ~/gitlab/autopkg-build   master ●  cat /tmp/receipts/Xcode.munki-receipt-20200727-154335.plist 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<dict>
		<key>RecipeError</key>
		<string>Unknown processor 'XcodeBuildNumberEmitter'.</string>
	</dict>
</array>
</plist>
```
I deleted and made again the override. I'm always getting this error and I can't find this processor.

**Comment by nmcspadden** [comment]
Whoops, sorry. I added it back in c007f8f3e7e683ea3b46fc90b3b5ff8a7e017efa. Can you test again and verify?

**Comment by LcTrKiD** [comment]
Hi!
Now I'm getting this error:
```Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2887, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2881, in main
    exit(subcommands[verb]["function"](argv))
  File "/usr/local/bin/autopkg", line 2327, in run_recipes
    search_github=make_suggestions,
  File "/usr/local/bin/autopkg", line 430, in load_recipe
    auto_pull=auto_pull,
  File "/usr/local/bin/autopkg", line 430, in load_recipe
    auto_pull=auto_pull,
  File "/usr/local/bin/autopkg", line 430, in load_recipe
    auto_pull=auto_pull,
  [Previous line repeated 982 more times]
  File "/usr/local/bin/autopkg", line 400, in load_recipe
    auto_pull=auto_pull,
  File "/usr/local/bin/autopkg", line 307, in locate_recipe
    recipe_file = find_recipe(name, override_dirs + recipe_dirs)
  File "/usr/local/bin/autopkg", line 205, in find_recipe
    return find_recipe_by_identifier(id_or_name, search_dirs) or find_recipe_by_name(
  File "/Library/AutoPkg/autopkglib/__init__.py", line 318, in find_recipe_by_identifier
    matches = glob.glob(pattern)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/glob.py", line 71, in _iglob
    for dirname in dirs:
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/glob.py", line 72, in _iglob
    for name in glob_in_dir(dirname, basename, dironly):
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/glob.py", line 83, in _glob1
    return fnmatch.filter(names, pattern)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/fnmatch.py", line 51, in filter
    pat = os.path.normcase(pat)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/posixpath.py", line 55, in normcase
    if not isinstance(s, (bytes, str)):
RecursionError: maximum recursion depth exceeded in __instancecheck__```
This happen using my override and the original recipe.

**Comment by nmcspadden** [comment]
Try deleting and recreating your override. That error suggests that a recipe identifier is also listed as its own parent, causing a recursion loop.

**Comment by LcTrKiD** [comment]
Hi Nick!
That solve the issue.
Thank you very much !!!!
